# Generated by Django 3.1.3 on 2020-11-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
