# Generated by Django 3.1.3 on 2020-11-30 17:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20201130_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='color',
            field=colorfield.fields.ColorField(default='#C0C0C0', max_length=18),
        ),
    ]
